### ISSUE TITLE
Allow the log file permissions to be optionally set

### ISSUE THREAD

**Issue by KnightAR** [ngoctp/laravel-query-logger#4]
Right now there's no way to set the file permission for the log file, I need to set the log to group writable but right now the default 0644 permission is being set.

**Comment by ngoctp** [comment]
Please upgrade to v1.0.8 and update your config file.

**Comment by ngoctp** [comment]
@KnightAR please check if it works as your expected. I'm going to close this issue.

**Comment by KnightAR** [comment]
Hi Thanks I will check on this .. sorry for the late reply.
